from .shallownet import ShallowNet
from .lenet import LeNet
from .minvggnet import MinVGGNet
from .shallownet_torch import ShallowNetTorch
from .fcheadnet import FCHeadNet
from .lenet_batchnorm import LeNetBatchNorm
from .alexnet import AlexNet
from .minigooglenet import MiniGoogleNet
from .deepergooglenet import DeeperGoogleNet
from .resnet import ResNet