---
title: "R Notebook"
author: mhasa
date: 7/4/2020
output: html_document
---






```{r}
require(astsa)
```



```{r}
plot(jj, type = "o", main = "JJ quarterly earning per share", ylab
  = "earnings", xlab = "years")
```
# pneumonia and influenza deaths -> monthly deaths in the US per 10_000 for 11 years 1968-1979
```{r}
plot(flu, main = "monthly pneumonia deaths in the US", ylab = "no. of death
 per 10_000 people", xlab = "months")
```
# globall mean land-ocean temperatures deviations
```{r}
plot(globtemp)
```
- there is increasing trend
- there is also some seasonality probably due to seasons over the year

```{r}
plot(globtempl)
```
# generate a TS random normal variables
```{r}
purely_random_process <- ts(rnorm(100))
purely_random_process
```
```{r}
plot(purely_random_process)
```
```{r}
acf(purely_random_process)
```
# simulation - random walk
```{r}
x = NULL
x[1] = 0
for (i in 2:1000) {
  x[i] = x[i - 1] + rnorm(1)
}

random_walk = ts(x)
plot(random_walk, main = "A random walk", ylab = " ", xlab = "days", col
  = "blue", lwd = 2)
```
```{r}
acf(random_walk)
```