from .simplepreprocesor import SimplePreProcessor
from .aspect_aware_processing import AspectAwarePreprocessor
from .imagetoarraypreprocesor import ImageToArrayPreprocessor
from .meanpreprocessor import MeanPreprocessor
from .patchpreprocessor import PatchPreprocessor
from .croppreprocessor import CropPreprocessor