---
title: "R Notebook"
author: mhasa
date: 6/30/2020
output: html_document
---


Import packages.
```{r}
library(faraway)
attach(worldcup)
```

```{r}
mean(worldcup$Time)
```
```{r}
small.size.dataset=c(91,49,76,112,97,42,70, 100, 8, 112, 95, 90, 78, 62, 56, 94, 65, 58, 109, 70, 109, 91, 71, 76, 68, 62, 134, 57, 83, 66)
```

```{r}
hist(small.size.dataset)
```
```{r}
hist(small.size.dataset, xlab='My data points', main='Histogram of my data', freq=F, col='green')
```
```{r}
hist(small.size.dataset, xlab='My data points', main='Histogram of my data', freq=F, col='green')
lines(density(small.size.dataset))
```
```{r}
hist(small.size.dataset, xlab='My data points', main='Histogram of my data', freq=F, col='green')
lines(density(small.size.dataset), col='red', lwd=5)
```
```{r}
hist(small.size.dataset, xlab='My data points', main='Histogram of my data', freq=F, col='green', breaks=10)
lines(density(small.size.dataset), col='red', lwd=5)
```
# scatterplot
```{r}
set.seed(2016)
test1_scores <- round(rnorm(n=50, mean=78, sd=10))
test2_scores <- round(rnorm(n=50, mean=78, sd=14))

plot(test2_scores~test1_scores,
     xlab = "test 1 score",
     ylab = "test 2 score",
     main = "Test Score Scatter of 50 Students")
```
```{r}
quiz_data=c(37, 86, 79, 95, 61, 93, 19, 98, 121, 26, 39, 11, 26, 75, 29,130, 42, 8)
hist(quiz_data)
```
```{r}
help(co2)
co2
```

```{r}
class(co2)
```
```{r}
plot(co2, main = "atmospheric co2")
```
```{r}
sleep
```
```{r}
help(trees)
trees
```